version: '3.10.11'

services:
  web:
    container_name: web-dev
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./backend:/Users/Admin/Documents/epistaime/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
