FROM python:3.10.11-alpine as builder

WORKDIR /Users/Admin/Documents/epistaime/backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc g++ python3-dev musl-dev

RUN pip install --upgrade pip
COPY ./requirements.txt .
COPY .env.EPM .
COPY .env.INFO .
RUN pip install -r requirements.txt
COPY . .







